name: 'Tag a commit'
description: 'Action to tag a commit'
author: 'Beez Innovation Labs'
inputs:
  tag:
    description: Tag Name
    required: true
  commit-sha:
    description: Commit sha to apply the tag to
    required: true
  token:
    description: PAT for accessing the application repo
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
